CREATE DATABASE COLLEGE;
USE COLLEGE;
DROP DATABASE COLLEGE;
CREATE TABLE STUDENT (USN VARCHAR (10) PRIMARY KEY, SNAME VARCHAR (25), ADDRESS VARCHAR (25), PHONE VARCHAR(15), GENDER VARCHAR (1));
CREATE TABLE SEMSEC (SSID VARCHAR (5) PRIMARY KEY, SEM INT, SEC VARCHAR (1));
CREATE TABLE CLASS (USN VARCHAR (10), SSID VARCHAR (5), PRIMARY KEY (USN, SSID), FOREIGN KEY (USN) REFERENCES STUDENT (USN), FOREIGN KEY (SSID) REFERENCES SEMSEC (SSID));
CREATE TABLE SUBJECT ( SUBCODE VARCHAR (8), TITLE VARCHAR (20), SEM INT, CREDITS INT, PRIMARY KEY (SUBCODE));
CREATE TABLE IAMARKS ( USN VARCHAR (10), SUBCODE VARCHAR (8), SSID VARCHAR (5), TEST1 INT, TEST2 INT, TEST3 INT, FINALIA INT, PRIMARY KEY (USN, SUBCODE, SSID), FOREIGN KEY (USN) REFERENCES STUDENT (USN), FOREIGN KEY (SUBCODE) REFERENCES SUBJECT (SUBCODE), FOREIGN KEY (SSID) REFERENCES SEMSEC (SSID));
SHOW TABLES;

INSERT INTO STUDENT VALUES ('1RN13CS020','AKSHAY','BELAGAVI', 8877881122,'M'); 
INSERT INTO SEMSEC VALUES ('CSE8A', 8,'A'); 
INSERT INTO CLASS VALUES ('1RN13CS020','CSE8A'); 
INSERT INTO SUBJECT VALUES ('10CS81','ACA', 8, 4); 
INSERT INTO IAMARKS VALUES ('1RN13CS091','10CS81','CSE8C', 15, 16, 18,16); 
SELECT * FROM STUDENT;
-- 1. List all the student details studying in fourth semester ‘C’ section.
 
SELECT S.*, SS.SEM, SS.SEC
FROM STUDENT S, SEMSEC SS, CLASS C WHERE S.USN = C.USN AND
SS.SSID = C.SSID AND
SS.SEM = 4 AND SS.SEc='C';

-- 2. Compute the total number of male and female students in each semester and in each section

SELECT SS.SEM, SS.SEC, S.GENDER, COUNT(S.GENDER) AS COUNT FROM STUDENT S, SEMSEC SS, CLASS C
WHERE S.USN = C.USN AND
SS.SSID = C.SSID
GROUP BY SS.SEM, SS.SEC, S.GENDER ORDER BY SEM;

-- 3. Create a view of Test1 marks of student USN ‘1BI15CS101’ in all subjects. 

CREATE VIEW STU_TEST1_MARKS_VIEW AS
SELECT TEST1, SUBCODE
FROM IAMARKS
WHERE USN = '1RN13CS091';

select * from STU_TEST1_MARKS_VIEW ;

-- 4. Calculate the FinalIA (average of best two test marks) and update the corresponding table for all students.
UPDATE IAMARKS
SET FINALIA = (TEST1 + TEST2 + TEST3) / 3;

SELECT * FROM IAMARKS;

-- 5. Categorize students based on the following criterion: 
-- If FinalIA = 17 to 20 then CAT = ‘Outstanding’ 
-- If FinalIA = 12 to 16 then CAT = ‘Average’ 
-- If FinalIA< 12 then CAT = ‘Weak’ 
-- Give these details only for 8th semester A, B, and C section students.

SELECT S.USN,S.SNAME,S.ADDRESS,S.PHONE,S.GENDER, (CASE
WHEN IA.FINALIA BETWEEN 17 AND 20 THEN 'OUTSTANDING'
WHEN IA.FINALIA BETWEEN 12 AND 16 THEN 'AVERAGE' 
ELSE 'WEAK' END) AS CAT
FROM STUDENT S, SEMSEC SS, IAMARKS IA, SUBJECT SUB WHERE S.USN = IA.USN AND
SS.SSID = IA.SSID AND
SUB.SUBCODE = IA.SUBCODE AND
SUB.SEM = 8;